apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  labels:
    appName: mb-service-1-prod
  name: mb-service-1-prod
  namespace: ns-master-builder-1
  annotations:
    strategy.spinnaker.io/max-version-history: '2'
spec:
  replicas: 3
  selector:
    matchLabels:
      appName: mb-service-1-prod
  template:
    metadata:
      labels:
        appName: mb-service-1-prod
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                  - key: lifecycle
                    operator: In
                    values:
                      - OnDemand
              weight: 1
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: intent
                    operator: In
                    values:
                      - prod-high-risk
      containers:
        - image: 693885100167.dkr.ecr.us-east-2.amazonaws.com/master-builder/sample-service-1:v5
          name: mb-service-1-prod
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 1024m
              memory: 512Mi
            requests:
              cpu: 1024m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
